services:

  database:
    image: postgres-school
    container_name: postgres-db
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    image: simple-api
    container_name: simple-api
    networks:
      - app-network
      - proxy-network
    env_file:
      - .env
    depends_on:
      - database

  httpd:
    build: ./httpd
    image: tp01-reverse-proxy
    container_name: reverse-proxy
    networks:
      - proxy-network
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  app-network:
  proxy-network: