- name: Run PostgreSQL container
  community.docker.docker_container:
    name: postgres-db
    image: xiangyuyan/tp-devops-database:latest
    state: started
    restart_policy: always

    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd

    networks:
      - name: app-network

    volumes:
      - postgres-data:/var/lib/postgresql/data

    published_ports:
      - "5432:5432"
