- hosts: all
  gather_facts: true
  become: true

  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python

  roles:
    - docker
    - network
    - database
    - backend
    - proxy



  tasks:

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-venv
          - python3-pip
        state: latest
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Create Docker virtual env
      command: python3 -m venv /opt/docker_venv
      args:
        creates: /opt/docker_venv

    - name: Install Docker SDK
      command: /opt/docker_venv/bin/pip install docker

    - name: Ensure Docker running
      service:
        name: docker
        state: started
