ServerName localhost

DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

ProxyPreserveHost On

ProxyPass "/departments" "http://backend:8080/departments"
ProxyPassReverse "/departments" "http://backend:8080/departments"