ServerName localhost

ProxyPreserveHost On

ProxyPass "/departments" "http://simple-api:8080/departments"
ProxyPassReverse "/departments" "http://simple-api:8080/departments"

ProxyPass "/" "http://simple-api:8080/"
ProxyPassReverse "/" "http://simple-api:8080/"