name: Publish Docker images

on:
  workflow_run:
    workflows:
      - Test backend and SonarCloud
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

  build-and-push-database:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build database image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

  build-and-push-httpd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:v${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest