name: Test backend and SonarCloud

on:
  push:
    branches:
      - main
      - develop
      - test-deployment-update
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Give execute permission
        working-directory: ./simple-api
        run: chmod +x mvnw

      - name: Build and test with Maven
        working-directory: ./simple-api
        run: ./mvnw clean verify

      - name: Upload Maven test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: simple-api/target/surefire-reports/

  sonar:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Give execute permission
        working-directory: ./simple-api
        run: chmod +x mvnw

      - name: Run SonarCloud analysis
        working-directory: ./simple-api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw verify sonar:sonar \
            -Dsonar.projectKey=XiangyuYan-1_DevOps \
            -Dsonar.organization=xiangyuyan-1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN